# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Sing Me a Dress' do

end

target 'Sing Me a DressTests' do

end

target 'Sing Me a DressUITests' do

end


pod 'Firebase', '>= 2.5.0'
